n  = input('Digite algo: ')
print(n.isnumeric())
print(n.isalpha())
print(n.isalnum())
print(n.isupper())
n  = bool(input('Digite um numero: '))
print(type(n))
n  = input('Digite outro numero: ')
print(type(n))
