a = input('Digite algo:')
print('É somente numeros?', a.isnumeric())
print('É somente letras?', a.isalpha())
print('tem letras e numeros?', a.isalnum())
print(' ta tudo maiusculo?', a.isupper())
print('ta tudo minusculo?', a.islower())
