frase = 'Curso em Video Python'
print('='*20)
print('FATIAMENT0')
print((frase[3]))
print(frase[3:13])
print(frase[:13])
print(frase[::2])
print('='*20)
print('ANÁLIZE')
print(frase.count('o'))
print(len(frase))
print(frase.find('deo'))
print(frase.find('Android'))
print('='*20)
print('TRASFORMAÇÂO')
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print('='*20)
print('DIVISÃO')
print(frase.split())
print(frase.split(' ',2))
print(frase.rsplit(' ',2))
print('='*20)
print('JUNÇÃO')
print('~'.join(frase))
