n1 = int(input('Digite um numero: '))
n2 = int(input('Digite outro: '))
n3 = int(input('Só mais um: '))
print('O numero maior é {}.'.format(max(n1,n2,n3)))
print('O numero menor é {}.'.format(min(n1,n2,n3)))
